# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf947b50b21fa8a260e35290137d6a2006a11f5da4b96d442c1f9c4d4e60a602d4ca6b893498a3120a812924da89693efdbbb4fbdbb9b1d9b17cde1ec397da5d

test:
  secret_key_base: 9aa51c593cd69d52f6d050e75488edea112a44a4252116d37ac94ac8d7d1fc229aeb66dfa2555cea4203e49957439e92aafc2fea673173c2c21aca9b45701666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
