# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c91a4e547a35d821fd31722a85caf06078162158a44d2dd6f7d47c681acc3a6af38d896d51f516c30f9ca85e3c494af9cace1661c03c394cc1b460588345e8c

test:
  secret_key_base: bae5556ce860a48a16d35d74deb70d4ac8eb01df63a1ce3e9833824c9913091f01af72a1044487f4a3efc2b88eee228ba721ad20cccd5ec7d01fa8b31cc771e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
